pass over bin and configuration

diff --git a/bin/check-pdns b/bin/check-pdns
--- a/bin/check-pdns
+++ b/bin/check-pdns
@@ -1,20 +1,13 @@
-#!/usr/bin/env python3
-# -*- coding: utf-8 -*-
+#!/bin/sh
 
-import subprocess
+PDNS_CONTROL_CMD="/usr/local/bin/pdns_control"
 
-import memcache
-
-
-PDNS_CONTROL = '/usr/local/bin/pdns_control'
-
-
-ret_code = subprocess.call([PDNS_CONTROL, 'status'], 
-                           stderr=subprocess.DEVNULL,
-                           stdout=subprocess.DEVNULL)
-if ret_code != 0:
-    print('pdns is not running')
-    exit(1)
-
-print('all checks passed')
+$PDNS_CONTROL_CMD status ; EC=$?
+if test "$EC" != "0"
+then
+    echo "failed!"
+    exit 1
+else
+    echo "ok"
+fi
 
diff --git a/bin/polaris-health b/bin/polaris-health
--- a/bin/polaris-health
+++ b/bin/polaris-health
@@ -11,10 +11,9 @@
 # Description:       Polaris Health
 ### END INIT INFO
 
-POLARIS_INSTALL_PREFIX=/opt/polaris
-export POLARIS_INSTALL_PREFIX
+. /etc/default/polaris
 
-POLARIS_CONTROL_CMD="$POLARIS_INSTALL_PREFIX/bin/phealth-control"
+POLARIS_CONTROL_CMD="$POLARIS_INSTALL_PREFIX/bin/polaris-health-control"
 
 doControl()
 {
@@ -87,7 +86,7 @@ case "$1" in
             exit 1
         fi
 
-        doControl stop 
+        doControl stop  
         sleep 2
         doControl start
         sleep 2
@@ -101,8 +100,52 @@ case "$1" in
         fi
     ;;
 
+    get-generic-state)
+        doControl get-generic-state ; EC=$?
+        if test "$EC" != "0"
+        then    
+            echo "failed to get!"
+            exit 1
+        else
+            echo "$ret"
+        fi
+    ;;
+
+    get-ppdns-state)
+        doControl get-ppdns-state ; EC=$?
+        if test "$EC" != "0"
+        then
+            echo "failed to get!"
+            exit 1
+        else
+            echo "$ret"
+        fi
+    ;;
+
+    get-heartbeat)
+        doControl get-heartbeat ; EC=$?
+        if test "$EC" != "0"
+        then 
+            echo "failed to get!"
+            exit 1
+        else
+            echo "$ret"
+        fi
+    ;;
+
+    check-heartbeat)
+        doControl check-heartbeat ; EC=$?
+        if test "$EC" != "0"
+        then
+            echo "failed!"
+            exit 1
+        else 
+            echo "ok"
+        fi
+    ;;
+
     *)
-    echo polaris-health [status\|start\|start-debug\|stop\|restart]
+    echo polaris-health [status\|start\|start-debug\|stop\|restart\|get-generic-state\|get-ppdns-state\|get-heartbeat\|check-heartbeat]
     ;;
 
 esac
